### ISSUE TITLE
Question : Is there Java Wrapper for libpmemlog?

### ISSUE THREAD

**Issue by JerryYangSH** [pmem/pcj#17]
Actually I have two questions (to support Java):
1. I am wondering is there any java wrapper for [libpmemlog](https://github.com/pmem/pmdk/tree/7fd1ce3c620165df2da4568d48e94607b3832065/src/libpmemlog)?  I can not find these stuff in PCJ.

2. I assume PersistentLinkedQueue has same funcition as libpmemlog. like add / append, or pop / truncate... When I need a LogStore in Persistent Memory , between PersistentLinkedQueue and libpmemlog, which one should I choose ?  In term of performance, any data?

**Comment by asonje** [comment]
Hi,
There is currently no java wrapper for libpmemlog. The PersistentLinkedQueue can be used as a persistent log however I do not have performance data to compare this against libpmemlog. If your LogStore is a production application i dont recommend choosing the PersistentLinkedQueue as PCJ is an experimental library. [LLPL](https://github.com/pmem/llpl) is another persistent memory library for java that you could use to build a custom log store; this would be easier than creating a java wrapper.

**Comment by JerryYangSH** [comment]
@asonje Thanks for reply.
I am trying to do experiment porting Raft stack onto Persistent Memory.  One of required function is LogStore. It looks LLPL is kind of low level which needs extra work to  build datastructures like what PCJ provides. I am not sure how much effort it requires to build something advanced out of LLPL.

**Comment by asonje** [comment]
In that case the wrapper around pmemlog is a good starting point. We will have sample data structures in LLPL soon.
