### ISSUE TITLE
make test failed but PMDK simple copy works fine

### ISSUE THREAD

**Issue by gwnet** [pmem/pcj#23]
root@ubuntu:/home/wayne/pmem/pcj# sudo make tests
/usr/lib/jvm/java-8-openjdk-amd64/bin/javac  -Xlint:unchecked -XDenableSunApiLintControl -proc:none -d target/test_classes -cp src:target/classes:lib:src:lib/ST-4.0.8.jar: src/test/java/tests/PersistentLinkedQueueTest.java src/test/java/tests/TestCases.java src/test/java/tests/PersistentSIHashMapTest.java src/test/java/tests/PersistentFPTree2Test.java src/test/java/tests/PersistentArrayTest.java src/test/java/tests/PersistentTestRunner.java src/test/java/tests/ObjectDirectoryTest.java src/test/java/tests/PersistentFPTree1Test.java src/test/java/tests/PersistentHashMapTest.java src/test/java/tests/PersistentTupleTest.java src/test/java/tests/PersistentAtomicReferenceTest.java src/test/java/tests/PersistentSkipListMapTest.java src/test/java/tests/MultithreadTest.java src/test/java/tests/PersistentLinkedListTest.java src/test/java/tests/PersistentByteBufferTest.java src/test/java/tests/PersistentArrayListTest.java
/usr/lib/jvm/java-8-openjdk-amd64/bin/java  -ea -cp target/classes:lib:src:lib/ST-4.0.8.jar::target/test_classes:src -Djava.library.path=target/cppbuild tests.PersistentTestRunner
Opening heap... Encountered error opening pool. Please check if /mnt/mem/persistent_heap exists and accessible.
make: *** [Makefile:84: tests] Error 255
root@ubuntu:/home/wayne/pmem/pcj# sudo make tests
/usr/lib/jvm/java-8-openjdk-amd64/bin/javac  -Xlint:unchecked -XDenableSunApiLintControl -proc:none -d target/test_classes -cp src:target/classes:lib:src:lib/ST-4.0.8.jar: src/test/java/tests/PersistentLinkedQueueTest.java src/test/java/tests/TestCases.java src/test/java/tests/PersistentSIHashMapTest.java src/test/java/tests/PersistentFPTree2Test.java src/test/java/tests/PersistentArrayTest.java src/test/java/tests/PersistentTestRunner.java src/test/java/tests/ObjectDirectoryTest.java src/test/java/tests/PersistentFPTree1Test.java src/test/java/tests/PersistentHashMapTest.java src/test/java/tests/PersistentTupleTest.java src/test/java/tests/PersistentAtomicReferenceTest.java src/test/java/tests/PersistentSkipListMapTest.java src/test/java/tests/MultithreadTest.java src/test/java/tests/PersistentLinkedListTest.java src/test/java/tests/PersistentByteBufferTest.java src/test/java/tests/PersistentArrayListTest.java
/usr/lib/jvm/java-8-openjdk-amd64/bin/java  -ea -cp target/classes:lib:src:lib/ST-4.0.8.jar::target/test_classes:src -Djava.library.path=target/cppbuild tests.PersistentTestRunner
Opening heap... Encountered error opening pool. Please check if /mnt/mem/persistent_heap exists and accessible.
make: *** [Makefile:84: tests] Error 255
root@ubuntu:/home/wayne/pmem/pcj# 

===PMDK simple copy works fine===
wayne@ubuntu:~/pmdk/src/examples/libpmem$ sudo ./simple_copy /mnt/mem/1.txt /mnt/mem/2.txt
wayne: /mnt/mem/1.txt src-file
wayne: /mnt/mem/2.txt  dst-file

**Comment by asonje** [comment]
Hi,
what is the size of the pool as specified in your 'config.properties' file? Verify that there is enough memory on your mount point to accommodate it.

**Comment by gwnet** [comment]
I already fix this by change the configure file. thank you so much
